version: '3'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=spacedb
    volumes:
      - ./initdb/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres

volumes:
  postgres_data:
    driver: local